apiVersion: skaffold/v2beta27
kind: Config
deploy:
  # kubeContext: "minikube"
  kubeContext: "docker-desktop"
  helm:
    releases:
    # TODO create chart museum and draw from there
    - name: co-api
      version: ~0.0.3
      chartPath: ../k8s/core/helm/api
      namespace: co-dev
      createNamespace: true
      artifactOverrides:
        image: curioushuman/curious-outcomes-api
      imageStrategy:
        helm: {}
    - name: co-web
      version: ~0.0.1
      chartPath: ../k8s/core/helm/web
      namespace: co-dev
      # createNamespace: true
      artifactOverrides:
        image: curioushuman/curious-outcomes-web
      imageStrategy:
        helm: {}
build:
  local:
    push: false
  artifacts:
    - image: curioushuman/curious-outcomes-api
      context: .
      docker:
        dockerfile: apps/api/Dockerfile
        target: test
      sync:
        manual:
          - src: 'apps/api/src/**/*.ts'
            dest: '/usr/src/app/'
          - src: 'libs/shared/**/*.ts'
            dest: '/usr/src/app/'
    - image: curioushuman/curious-outcomes-web
      context: .
      docker:
        dockerfile: apps/web/Dockerfile
        target: test
      sync:
        manual:
          - src: 'apps/web/src/**/*.ts'
            dest: '/usr/src/app/'
