### Test for readiness
GET http://curious-outcomes.dev/api/ping


### Users
POST http://curious-outcomes.dev/api/users


### PROD: Test for readiness
GET https://api.curious-outcomes.community/api/ping


### STAGING: Test for readiness
GET http://api-staging.curious-outcomes.community/api/ping
